# Generated by Django 2.2.13 on 2020-08-31 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perms', '0016_auto_20200817_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grantednode',
            old_name='asset_granted_count',
            new_name='asset_granted_ref_count',
        ),
        migrations.RenameField(
            model_name='grantednode',
            old_name='granted_count',
            new_name='granted_ref_count',
        ),
    ]
