# Generated by Django 2.2.13 on 2020-08-31 06:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perms', '0017_auto_20200831_1032'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GrantedNode',
            new_name='MappingNode',
        ),
    ]
