# Generated by Django 2.2.13 on 2020-08-31 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perms', '0020_auto_20200831_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='toupdatenode',
            name='action',
            field=models.CharField(default='', max_length=32),
        ),
    ]
