# Generated by Django 2.2.13 on 2020-08-31 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0058_fill_node_value_assets_amount_and_parent_key'),
        ('perms', '0021_toupdatenode_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingnode',
            name='node',
            field=models.ForeignKey(db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.Node'),
        ),
        migrations.AddField(
            model_name='mappingnode',
            name='parent_key',
            field=models.CharField(db_index=True, default='', max_length=64, verbose_name='Parent key'),
        ),
    ]
