# Generated by Django 2.2.13 on 2020-09-01 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perms', '0022_auto_20200831_2057'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToUpdateNode',
            new_name='UpdateMappingNodeTask',
        ),
        migrations.AlterField(
            model_name='mappingnode',
            name='node',
            field=models.ForeignKey(db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mapping_nodes', to='assets.Node'),
        ),
    ]
