# Generated by Django 2.2.13 on 2020-09-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perms', '0023_auto_20200901_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingnode',
            name='node_granted_ref_count',
            field=models.IntegerField(default=0),
        ),
    ]
