# Generated by Django 2.2.13 on 2020-09-04 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perms', '0024_mappingnode_node_granted_ref_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='RebuildUserTreeTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, max_length=32, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=32, null=True, verbose_name='Updated by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='mappingnode',
            name='asset_granted_ref_count',
        ),
        migrations.RemoveField(
            model_name='mappingnode',
            name='granted_ref_count',
        ),
        migrations.RemoveField(
            model_name='mappingnode',
            name='node_granted_ref_count',
        ),
        migrations.AddField(
            model_name='mappingnode',
            name='asset_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mappingnode',
            name='asset_granted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.DeleteModel(
            name='UpdateMappingNodeTask',
        ),
    ]
