# Generated by Django 2.2.13 on 2020-09-04 05:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0058_fill_node_value_assets_amount_and_parent_key'),
        ('perms', '0025_auto_20200904_1316'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MappingNode',
            new_name='UserGrantedMappingNode',
        ),
    ]
